/**
 * BUILD-TIME blog fetch (runs as `prebuild`, before `ng build`).
 *
 * Pulls published posts from Sanity, renders their Portable Text bodies to
 * plain HTML, and writes everything into a generated TypeScript data file:
 *
 *     src/app/pages/blog/blog-data.generated.ts
 *
 * Why this design?
 *  • The Angular app imports that file, so post content is baked into the
 *    static, prerendered HTML → PERFECT SEO.
 *  • Your VISITORS never call Sanity (the data is in your own build output),
 *    so your Sanity free tier is essentially never touched.
 *  • Adding/editing a post = edit in Sanity Studio → trigger a rebuild → done.
 *
 * Heavy libs (@sanity/*) live in devDependencies and run ONLY here, so the
 * browser bundle stays lean.
 */
import { createClient } from '@sanity/client';
import { createImageUrlBuilder } from '@sanity/image-url';
import { toHTML } from '@portabletext/to-html';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const projectId = process.env.SANITY_PROJECT_ID || 'wzunc2e4';
const dataset = process.env.SANITY_DATASET || 'production';
// Optional read token — only needed if your dataset is PRIVATE.
const token = process.env.SANITY_API_READ_TOKEN || undefined;

const client = createClient({
  projectId,
  dataset,
  apiVersion: '2024-01-01',
  // Build-time read: go straight to the live API (always fresh) rather than the
  // cached CDN. This project requires a token to read content via the API, so
  // set SANITY_API_READ_TOKEN (a read-only "Viewer" token) in your env / Vercel.
  useCdn: false,
  token,
});

const builder = createImageUrlBuilder({ projectId, dataset });
const escapeHtml = (s = '') =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

/** Custom renderers so CMS code blocks + images match the site's styling. */
const components = {
  types: {
    image: ({ value }) => {
      const url = builder.image(value).width(1280).fit('max').auto('format').url();
      const alt = escapeHtml(value?.alt || '');
      const caption = value?.caption
        ? `<figcaption>${escapeHtml(value.caption)}</figcaption>`
        : '';
      return `<figure class="post-figure"><img src="${url}" alt="${alt}" loading="lazy" />${caption}</figure>`;
    },
    // From the @sanity/code-input plugin → renders like the site's dark code blocks.
    code: ({ value }) => {
      const lang = value?.language || 'text';
      const label = value?.filename || lang;
      return `<pre data-label="${escapeHtml(label)}"><code class="language-${escapeHtml(
        lang
      )}">${escapeHtml(value?.code || '')}</code></pre>`;
    },
  },
};

// GROQ: every post that has a slug, newest first.
const query = `*[_type == "post" && defined(slug.current)] | order(publishedAt desc){
  _id, title, "slug": slug.current, excerpt, tag, category, publishedAt, readMins,
  coverImage, body, seo
}`;

async function main() {
  // This project requires a token to read content. Without one, DON'T overwrite
  // the existing generated file — keep the last good data so the build (incl.
  // Vercel without the env var set) never accidentally ships an empty blog.
  if (!token) {
    console.warn('[fetch-blog] No SANITY_API_READ_TOKEN set — keeping existing generated data (skipping fetch).');
    return;
  }

  let raw;
  try {
    raw = await client.fetch(query);
  } catch (err) {
    // On a network/auth error, also keep the last good data rather than wiping it.
    console.warn('[fetch-blog] Fetch failed — keeping existing generated data.', err?.message);
    return;
  }

  const posts = (raw || []).map((p) => ({
    id: p._id,
    title: p.title || 'Untitled',
    slug: p.slug,
    excerpt: p.excerpt || '',
    tag: p.tag || 'POST',
    category: p.category || '',
    publishedAt: p.publishedAt || '',
    readMins: p.readMins || 5,
    coverUrl: p.coverImage
      ? builder.image(p.coverImage).width(1200).height(630).fit('crop').auto('format').url()
      : null,
    coverAlt: p.coverImage?.alt || p.title || '',
    bodyHtml: toHTML(p.body || [], { components }),
    seo: {
      metaDescription: p.seo?.metaDescription || p.excerpt || '',
      keywords: p.seo?.keywords || '',
    },
  }));

  const header = `// AUTO-GENERATED by scripts/fetch-blog.mjs — DO NOT EDIT BY HAND.
// Regenerated on every build from your Sanity content.

/** One blog post, with its body pre-rendered to HTML at build time. */
export interface GeneratedPost {
  id: string;
  title: string;
  slug: string;
  excerpt: string;
  tag: string;
  category: string;
  publishedAt: string;
  readMins: number;
  coverUrl: string | null;
  coverAlt: string;
  bodyHtml: string;
  seo: { metaDescription: string; keywords: string };
}

`;

  const body = `export const BLOG_POSTS: GeneratedPost[] = ${JSON.stringify(posts, null, 2)};\n`;

  const __dirname = dirname(fileURLToPath(import.meta.url));
  const outPath = join(__dirname, '..', 'src', 'app', 'pages', 'blog', 'blog-data.generated.ts');
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, header + body, 'utf8');

  console.log(`[fetch-blog] Wrote ${posts.length} post(s) → ${outPath}`);
}

main();
